### ISSUE TITLE
FormItem isTouched requirement unnecessary and hides actual valid errors

### ISSUE THREAD

**Issue by jwmann** [jannikbuschke/formik-antd#21] opened 2019-04-23 01:57 UTC
I'm current working on a form that uses both inline and form-wide validation.
I'm trying to cover all cases of someone using the form and trying to pass validation.

One scenario being, someone who doesn't fill out the form of required fields, and just presses submit and/or triggers the validateForm() function.

Using the current state of the FormItem component, even though Formik is legitimately passing proper errors, because the FormItem is checking for `isTouched`, it won't actually display any of the errors. So the user actually doesn't know why he can't submit (even though there are errors)

This needs to be fixed asap imo

**Comment by jannikbuschke** [comment] 2019-04-23 08:13
I tried reproducing with the `SubmitButton` component: https://codesandbox.io/s/mjkkxqlm9y
The form correctly shows validation errors, even if they previously had not been touched. The validation errors are shown, as using the `SubmitButton` yields all fields being marked as `touched`.

The SubmitButton calls formik.setSubmitting(). I guess then formik marks everything as touched

**Comment by jannikbuschke** [comment] 2019-04-23 08:15
Removing the `isTouched` condition would also lead to a problem when the whole form is validated at once. I.e. I usually use remote validation that validates all fields and gives one validation object back. The fields that had not been touched yet should not show errors messages (bad UX).

**Comment by jwmann** [comment] 2019-04-23 15:03
That's strange, I didn't know Submit would mark all fields as touched.
The problem is, I don't technically want to submit just yet.
There's another section to my form before that happens.

However, I suppose I can work around this.

Thank you for the discussion. I will close this for now.

**Comment by JeffJankowski** [comment] 2019-05-31 05:39
I'm hitting this issue as well. My use case is that I have a radio that adds additional, required fields to the form. A Formik error is generated that the field is missing, and the submit button is correctly disabled. However, since the `validationStatus` is not set, there is no feedback for the user. Additionally, the user can't trigger the validation through submission since the button is disabled.

Removing the `isTouched` condition solved my issue, and I'm not sure of a workaround. Can we consider adding a prop flag for this feature?

**Comment by jannikbuschke** [comment] 2019-05-31 08:27
Would enabling the `SubmitButton` be a solution (or at least workaround) for this case?
I.e. you can do `<SubmitButton disabled={false} />` (https://codesandbox.io/s/x2941k7vpz) to override the default behavior (SubmitButton is only enabled if form is dirty).

**Comment by jwmann** [comment] 2019-05-31 15:58
`<SubmitButton disabled={false} />` probably be the best way to get around this in your case.
You could even add extra logic if you feel it ruins the rest of your form.

In my case, I fixed my issue by using Formik's `setFieldTouched` method to manually set the field touched when I need it to show validation.

**Comment by JeffJankowski** [comment] 2019-06-01 03:41
Thanks for the suggestions and quick responses, guys. Really helpful library! 

I would prefer if the submit button stay disabled as the current functionality gives an additional cue to the user that the form is invalid, and preventing that action feels like good UX. I'll probably take @jwmann suggestion and manually touch the field, though I was hesitant to add another another hook into the change handlers (there's already a lot going on with form field mapping and input masks).

I think the logical place to touch new fields that require validation would be in Formik's `validate()`, but that function doesn't have scope into the `FormikBag` with the needed utility methods.

**Comment by jannikbuschke** [comment] 2019-06-01 10:34
Imho what is currently kind of missing is validation feedback that goes beyond FormItem. FormItem provides validation for simple fields (that exist on the form).
More complex scenarios might require extra `<ValidationMessages>` components that can render messages for things that are not directly link-able to single fields (maybe a combination of values is not allowed, or there is some more complex server-side validation thing that is not easily doable on the client-side) or somehow not really existent.

On this topic I am also thinking about the scope/boundary of this library. I am not sure if I really want to provide a lot of opinionated controls/features that require a lot of documentation/thinking/tweaking.
At the core of this lib are the input controls that are bound by the _name_ prop. Meant to be a 80-90% solution for simple forms.

SubmitButton and RefreshButton are added bonuses to provide a solution for simple cases. It is also totally fine to come up with a custom SubmitButton (the source code of this lib is pretty easy and straight forward imho, thanks to formik / ant d and the nature of React).

**Comment by JeffJankowski** [comment] 2019-06-05 01:48
**FYI:** I ended up having to create my own `FormItem` component and strip out the touched checks. It was becoming too cumbersome to manually touch all the fields (nested, arrays, etc). Additionally, whenever the form is reset (eg. user hits the cancel button), Formik clears the touched state as well.

**Comment by gabrielberlanda** [comment] 2019-06-14 12:29
@JeffJankowski Could you please share your solution?

**Comment by JeffJankowski** [comment] 2019-06-16 08:16
@gabrielberlanda You can modify [FormItem.tsx](https://github.com/jannikbuschke/formik-antd/blob/master/src/FormItem.tsx) by either copying the file from git and referencing it as needed, or you can use npm module `patch-package` to manipulate `node_modules` in-place. If you go with cloning the file, you'll need to fix the `lodash.get` reference if you don't already have `lodash` installed. With `patch-package` there's probably a way to modify the Typescript files, but I didn't look into it and just patched the transpiled js.

Either way, I did something like this:

```
const error = get(errors, name, undefined);
return (
  <Form.Item
    validateStatus={
      error
        ? 'error'
        : showValidateSuccess
        ? 'success'
        : undefined
    }
    help={error}
    {...restProps}
  >
    {children}
  </Form.Item>
);
```

**Comment by tiagombrito** [comment] 2020-04-17 13:00
> I tried reproducing with the `SubmitButton` component: https://codesandbox.io/s/mjkkxqlm9y
> The form correctly shows validation errors, even if they previously had not been touched. The validation errors are shown, as using the `SubmitButton` yields all fields being marked as `touched`.
> 
> The SubmitButton calls formik.setSubmitting(). I guess then formik marks everything as touched

I know this issue is old, but i'm having the same problem, and i hope this somehow helps.
In your codesandbox demo, if you remove the userName field from the initialValues (make initial values an empty object), the problem will show itself.
Maybe the workaround is just to set the fields to "" in the initialValues.

**Comment by jannikbuschke** [comment] 2020-04-25 07:44
Hi @tiagombrito .

Removing a property from initialValues looks suspicious to me. Why would you want to do that?

When the initialValue is missing, i.e. if it is undefined (not that setting it to null would work), then formik seems to not set this field as 'touched', and therefore we don't show it (in default mode only validation errors of touched fields are shown, which makes a lot of sense).

**Closed** 2020-05-24 04:55 UTC

**Comment by tiagombrito** [comment] 2020-05-25 10:20
Hello again @jannikbuschke 

I agree with what you said. My message was just to let people know that if they are having this issue, they need to add the initial variable as null (altho i remember having some value that was not working, i think it was an empty array, but changing it to a null worked).
Also, i'm just taking a guess, but i think this behaviour may be coming from formik and not with formik-antd.
