### ISSUE TITLE
Input.TextArea not working

### ISSUE THREAD

**Issue by jasyes** [jannikbuschke/formik-antd#183] opened 2021-04-15 04:08 UTC
I've just updated to Antd 4.15.1 and formik-antd Input.TextArea stop working.
When typing into textarea, the warning message display in console:

```
Warning: Formik called `handleChange`, but you forgot to pass an `id` or `name` attribute to your input:
    undefined
    Formik cannot determine which value to update. For more info see https://formik.org/docs/api/formik#handlechange-e-reactchangeeventany--void
```

Formik state not updating.

PS. On version 4.14.1 textArea working properly.

**Comment by jannikbuschke** [comment] 2021-04-15 09:42
probably duplicate of https://github.com/jannikbuschke/formik-antd/issues/182

**Closed by jannikbuschke** 2021-04-15 09:42 UTC
Labels: duplicate
