### ISSUE TITLE
Input.TextArea doesn't work

### ISSUE THREAD

**Issue by Chameleon45** [jannikbuschke/formik-antd#184] opened 2021-04-18 12:35 UTC
I have textarea in my form:
`<Form.Item name="selfDescription">
<Input.TextArea name="selfDescription" rows={4} showCount maxLength={500}  />
</Form.Item>`
and I actually can't enter any key in it. Also I receive this warning in console on each key entering in textarea:
![image](https://user-images.githubusercontent.com/50486434/115145331-b094b000-a059-11eb-8d63-96eaeb1e2e07.png)
Adding `onChange={(e) => (handleChange({ target: { name: 'selfDescription', value: e.target.value } }))` 
 to my Input.TextArea solves problem but I'm still receiving this warnings in my console and it is a bit confusing. So how can i properly fix this behavior?

**Comment by jannikbuschke** [comment] 2021-04-18 13:20
Probably a duplicate of https://github.com/jannikbuschke/formik-antd/issues/182

**Closed** 2021-04-18 13:27 UTC
Labels: duplicate
